
# artifacts - all the components will be saved in the artifacts directory

#define  artifacts

artifacts_root: artifacts

#data ingestion related configuration settings

data_ingestion:
  root_dir: artifacts/data_ingestion  # will create a directory and download data
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


# verifying the data files format before sending them to the model
data_validation: # data validation configuration
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt # status file will check status of the data file and return true or false
  ALL_REQUIRED_FILES: ["train", "test", "validation"]



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail




model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail




model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv